### ISSUE TITLE
Generate API Routing

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/ongenome_schema#7]
Need to discuss what API routes we would like.  @sdash-github would you mind posting the postgres queries you perform for the current application?  I will factor these into service endpoints.

**Comment by sdash-github** [comment]
From meeting with Andrew yesterday:
I recollect trying individual neighbors table per dataset.  Then, all I have to do is to query it from within the module script.  Why API?

**Comment by ctcncgr** [comment]
I believe we had decided yesterday that the API was a good idea as it allows for incorporation and routing outside of chado and tripal.  Do you remember this differently?

**Comment by ctcncgr** [comment]
Hey All,

So I think we can backburner this right now now.  I will work on this later if we decide we need it.

**Comment by adf-ncgr** [comment]
Thanks guys- just to close the loop on this here is my understanding of the situation (no need to comment unless you see it otherwise):
the "individual neighbors table per dataset" model is pretty close to what Sudhansu has already implemented using direct queries in his prototype, so there is probably relatively little effort to get things up and running using the direct query method. But, if at some point we may want other non-tripal clients to be able to access the same data, then we might do some refactoring to make this a service (aka API); whether we decide that the service implementation should be done using tripal or some other framework can be left until we decide we need to do the refactoring to support it, or if the current database implementation proves to be problematic for some reason and the service implementation gets more complex.
